---
title: "PR_landscape_metrics"
output: html_document
---

```{r libraries, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(terra)
library(tidyverse)
library(ggspatial)
library(landscapemetrics)

```

```{r data_setup}

farms <- read.csv("./Data/PR_farms27.csv")

farms.sf <- st_as_sf(farms,
                     coords = c(4, 3),
                     crs = st_crs(4326))

lf.evt <- rast("./Data/LF2016_EVT_200_PRVI/Tif/LV16_EVT_200.tif")

lf.evt.table <- cats(lf.evt)[[1]] 
# activeCat(lf.evt) <- "Value"  # set the active category of the raster DON'T 

# as.numeric turns the raster into a numeric layer based on 'Value'
lf.evt.num <- as.numeric(lf.evt)


```

```{r simplify_categories}
reclass.evt <- read.csv("evt_reclass.csv") %>% dplyr::select(EVT_NAME, reclass) %>%
  mutate(reclass.num = as.numeric(as.factor(reclass))) %>%
  left_join(lf.evt.table %>% rownames_to_column(var="evt.num")) %>% 
  mutate(evt.num = as.numeric(evt.num))

rcl.evt.mat <- reclass.evt %>% dplyr::select(Value, reclass.num) %>% as.matrix()

lf.class <- classify(lf.evt.num, rcl = rcl.evt.mat)

# check data to see if it works with landscape metrics
check_landscape(lf.class)

```

## Fix projection of farm data

```{r fix_data}

# transform the points to match the landscape layer
farms.pr <- st_transform(farms.sf, crs = crs(lf.class))

```

## calculate metrics for multiple radii and metrics

```{r multiple_buffers}
# buf.dist <- seq(100,1500, by=100) # buffer distances
# metrics <- c("lsm_l_area_mn", "lsm_c_ca", "lsm_l_ed", "lsm_l_te", "lsm_l_shape_mn", "lsm_l_contig_mn", "lsm_l_core_mn", "lsm_l_mesh", "lsm_l_division", "lsm_l_shdi", "lsm_l_pr", "lsm_l_shei", "lsm_l_contag")
# 
# 
# buffer.output <- list() # outputs for each buffer distance
# 
# for(i in 1:length(buf.dist)){
#   buffer.output[[i]] <- sample_lsm(landscape = lf.class, y = farms.pr,
#                             shape = "circle", size = buf.dist[i],
#                             what = "lsm_c_pland", 
#                             plot_id = farms.pr$PESTS_sitename)
# }
# 
# # add the metric ID to each distance table and combine tables
# lsmbuffers <- map2(buffer.output, buf.dist, ~.x %>% mutate(distance = .y)) %>%
#   bind_rows()
# 
# # here is a table describing the functions in the "metrics" vector
# metrics.details <- lsm_abbreviations_names %>% filter(function_name %in% metrics)
# metrics.details

# write to file
# write.csv(lsmbuffers, "lsmbuffers.csv", row.names = FALSE)
# write.csv(metrics.details, "metrics.csv", row.names = FALSE)
```

```{r extract_lc}
library(exactextractr)

buf.dist <- seq(100,1500, by=100) # buffer distances


areas <- list()
for(i in 1:length(buf.dist)){
  buf.i <- st_buffer(farms.pr, dist=buf.dist[i])
  
  areas[[i]] <- exact_extract(lf.class, buf.i, fun = "frac") %>% 
    bind_cols(farm=farms.pr %>% pull(PESTS_sitename))
  
  names(areas)[i] <- buf.dist[i]
}

areas.df <- bind_rows(areas, .id = "radius") %>% replace_na(list(frac_9=0, frac_6=0)) %>%
  relocate(farm)

# rename classes
reclasses <- reclass.evt %>% dplyr::select(reclass, reclass.num) %>% distinct() %>%
  mutate(fromname = paste0("frac_",reclass.num)) %>% dplyr::select(-reclass.num) %>% deframe()

areas.df <- areas.df %>% rename(!!!reclasses[which(reclasses %in% names(areas.df))])  # some columns aren't in reclasses and causes error

write.csv(areas.df, "landcover_buffers_update.csv", row.names = FALSE)
```

```{r ring}
library(rmapshaper)

make_ring <- function(sfpts, outerd, hole){
  rings <- list()
  for(g in 1:nrow(sfpts)){
    buf.g <- st_buffer(sfpts[g,], dist=outerd)
    hole.g <- st_buffer(sfpts[g,], dist=hole)
    rings[[g]] <- rmapshaper::ms_erase(buf.g, hole.g)
  }
  return(bind_rows(rings))
}

ring.dist <- c(100,200,500,1000,1500)

ring.areas <- list()
for(i in 2:length(ring.dist)){

  ring.i <- make_ring(farms.pr, ring.dist[i], ring.dist[i-1])
  
  ring.areas[[i-1]] <- exact_extract(lf.class, ring.i, fun = "frac") %>% 
    bind_cols(farm=farms.pr %>% pull(PESTS_sitename)) %>%
    mutate(inner.radius=ring.dist[i-1])
  
  names(ring.areas)[i-1] <- ring.dist[i]
}

ring.areas.df <- bind_rows(ring.areas, .id = "outer.radius") %>% 
  relocate(farm,inner.radius) 

ring.areas.df <- ring.areas.df %>% 
  rename(!!!reclasses[which(reclasses %in% names(ring.areas.df))])

write.csv(ring.areas.df, "landscape_rings_update.csv", row.names = FALSE)

```

```{r cover_buffers}

vegcov <- rast("./Data/LF2016_EVC_200_PRVI/Tif/LV16_EVC_200.tif")

vegcov.table <- cats(vegcov)[[1]] 

trcov <- ifel(vegcov<=100 | vegcov>200, 100, vegcov) %>% as.numeric() - 100
shrcov <- ifel(vegcov<200 | vegcov>264, 200, vegcov) %>% as.numeric() - 200
trshrcov <- trcov + shrcov

tr.areas <- list()
shr.areas <- list()
trshr.areas <- list()

for(i in 1:length(buf.dist)){
  buf.i <- st_buffer(farms.pr, dist=buf.dist[i])
  
  tr.areas[[i]] <- exact_extract(trcov, buf.i, fun = "mean", weights="area") %>% 
    bind_cols(farm=farms.pr %>% pull(PESTS_sitename)) %>%
    rename_with(.cols = 1, ~"pc_cov")
  
  shr.areas[[i]] <- exact_extract(shrcov, buf.i, fun = "mean", weights="area") %>% 
    bind_cols(farm=farms.pr %>% pull(PESTS_sitename)) %>%
    rename_with(.cols = 1, ~"pc_cov")
  
  trshr.areas[[i]] <- exact_extract(trshrcov, buf.i, fun = "mean", weights="area") %>% 
    bind_cols(farm=farms.pr %>% pull(PESTS_sitename)) %>%
    rename_with(.cols = 1, ~"pc_cov")
  
  names(tr.areas)[i] <- buf.dist[i]
  names(shr.areas)[i] <- buf.dist[i]
  names(trshr.areas)[i] <- buf.dist[i]
}

tr.areas.df <- bind_rows(tr.areas, .id = "radius") %>% 
  pivot_wider(id_cols = farm, values_from = pc_cov, 
              names_from = radius, names_prefix = "treecov_")

shr.areas.df <- bind_rows(shr.areas, .id = "radius") %>% 
  pivot_wider(id_cols = farm, values_from = pc_cov, 
              names_from = radius, names_prefix = "shrbcov_")

trshr.areas.df <- bind_rows(trshr.areas, .id = "radius") %>% 
  pivot_wider(id_cols = farm, values_from = pc_cov, 
              names_from = radius, names_prefix = "treeshrbcov_")

allcov.areas <- left_join(
  tr.areas.df, shr.areas.df, by = "farm"
) %>%
  left_join(trshr.areas.df, by = "farm")

write.csv(allcov.areas, "veg_cov_buffers_update.csv", row.names = FALSE)

```

```{r cover_rings}

tr.rings <- list()
shr.rings <- list()
trshr.rings <- list()

for(i in 2:length(ring.dist)){
  
  ring.i <- make_ring(farms.pr, ring.dist[i], ring.dist[i-1])
  
  tr.rings[[i-1]] <- exact_extract(trcov, ring.i, "mean", weights="area") %>% 
    bind_cols(farm=farms.pr %>% pull(PESTS_sitename)) %>%
    mutate(inner.radius=ring.dist[i-1]) %>%
    rename_with(.cols = 1, ~"pc_cov")
  
  shr.rings[[i-1]] <- exact_extract(shrcov, ring.i, "mean", weights="area") %>% 
    bind_cols(farm=farms.pr %>% pull(PESTS_sitename)) %>%
    mutate(inner.radius=ring.dist[i-1]) %>%
    rename_with(.cols = 1, ~"pc_cov")
  
  trshr.rings[[i-1]] <- exact_extract(trshrcov, ring.i, "mean", weights="area") %>% 
    bind_cols(farm=farms.pr %>% pull(PESTS_sitename)) %>%
    mutate(inner.radius=ring.dist[i-1]) %>%
    rename_with(.cols = 1, ~"pc_cov")
  
  names(tr.rings)[i-1] <- ring.dist[i]
  names(shr.rings)[i-1] <- ring.dist[i]
  names(trshr.rings)[i-1] <- ring.dist[i]
  
}

tr.rings.df <- bind_rows(tr.rings, .id = "outer.radius") %>% 
  mutate(ringsize = paste0(inner.radius,"-", outer.radius)) %>%
  pivot_wider(id_cols = farm, values_from = pc_cov, 
              names_from = ringsize, names_prefix = "treecov_")

shr.rings.df <- bind_rows(shr.rings, .id = "outer.radius") %>% 
  mutate(ringsize = paste0(inner.radius,"-", outer.radius)) %>%
  pivot_wider(id_cols = farm, values_from = pc_cov, 
              names_from = ringsize, names_prefix = "shrbcov_")

trshr.rings.df <- bind_rows(trshr.rings, .id = "outer.radius") %>% 
  mutate(ringsize = paste0(inner.radius,"-", outer.radius)) %>%
  pivot_wider(id_cols = farm, values_from = pc_cov, 
              names_from = ringsize, names_prefix = "treeshrbcov_")

allcov.rings <- left_join(
  tr.rings.df, shr.rings.df, by = "farm"
) %>%
  left_join(trshr.rings.df, by = "farm")

write.csv(allcov.rings, "veg_cov_rings_update.csv", row.names = FALSE)

```